<?php

namespace App\Repositories;

use App\Models\Product;
use App\Repositories\BaseRepository;

class ProductRepository extends BaseRepository
{
    protected $fieldSearchable = [
        'hide_it',
        'avail',
        'clearance',
        'new_icon',
        'kid_comp',
        'Item',
        'Name',
        'brand',
        'featured_item',
        'color_order',
        'deepstock',
        'item_des',
        'gift_box',
        'gb_dim',
        'lineup',
        'oz',
        'mL',
        'mirror',
        'insulation',
        'Pg',
        'keywords',
        'dishwasher',
        'microwave',
        'color',
        'color_search',
        'color_search2',
        'PMS',
        'hex',
        'Origin',
        'add_charge',
        'ACC',
        'add_charge_discount_id',
        'Category',
        'Material',
        'Style',
        'Style2',
        'short_name',
        'short_desc',
        'Pk',
        'Weight',
        'ItemHeight',
        'ItemWidth',
        'ItemWeight',
        'UPSH',
        'UPSW',
        'UPSL',
        'UPSwt',
        'UPSqty',
        'CaseDim',
        'MC',
        'MCDIM',
        'MCPrice',
        'MCQty',
        'MCWeight',
        'ImprintArea',
        'loc2',
        'imp2',
        'loc3',
        'imp3',
        'setup',
        'setup_discount_id',
        'included',
        'included_discount_id',
        'Qty1',
        'Price1',
        'Qty2',
        'Price2',
        'Qty3',
        'Price3',
        'Qty4',
        'Price4',
        'Qty5',
        'Price5',
        'EQP',
        'sale_exp',
        'concord',
        'Sale1',
        'Sale2',
        'Sale3',
        'Sale4',
        'Sale5',
        'SaleEQP',
        'show_canada',
        'CANqty1',
        'CAN1',
        'CANqty2',
        'CAN2',
        'CANqty3',
        'CAN3',
        'CANqty4',
        'CAN4',
        'CANqty5',
        'CAN5',
        'CANqty6',
        'CAN6',
        'CANqty7',
        'CAN7',
        'CANEQP',
        'canSALE1',
        'canSALE2',
        'canSALE3',
        'canSALE4',
        'canSALE5',
        'canSALE6',
        'canSALE7',
        'canSALEEQP',
        'alt_item1',
        'alt_item2',
        'alt_item3',
        'alt_item4',
        'foil',
        'top',
        'straw',
        'special_notes',
        'expires',
        'full_color',
        'h4',
        'd4',
        'laser',
        'GMB',
        'enviro',
        'enviro2',
        'template',
        'logo_tool',
        'compliance',
        'video',
        'video2',
        'lastChangeDate',
        'creationDate'
    ];

    public function getFieldsSearchable(): array
    {
        return $this->fieldSearchable;
    }

    public function model(): string
    {
        return Product::class;
    }

    
}
